image: gidotech/sqitch

stages:
  - gen
  - staging
  - production
  
gen:
  stage: gen
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$GIT_SSH_PKEY")
    - git config --global url."ssh://git@g.ghn.vn".insteadOf "https://gido.vn"
    - git config --global user.email "gitbot@gido.vn"
    - git config --global user.name "Mr. Robot"
    - export CI_PUSH_REPO=git$(echo $CI_REPOSITORY_URL | grep -o "@.*" | sed "s/\//:/")
    - echo $CI_PUSH_REPO
    - git remote set-url --push origin ${CI_PUSH_REPO}
    - git status
    - go get -u gido.vn/gic/databases/sqitch.git
  script:
    - sqitch.git -schema schema/schema.yml -name ${CI_COMMIT_SHORT_SHA} -d ${CI_COMMIT_SHA}
    - 'git branch -D tmp_branch || true'
    - git status
    - 'git checkout -b tmp_branch && git add sqitch.plan deploy/ && git commit -m "[ROBOT] Auto generate deploy from [${CI_JOB_ID}](${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID})" && git push origin tmp_branch:staging'
  only:
    refs:
      - staging
    - changes:
      - schema/tables/*
      - schema/dropped-tables/dropped-tables.yml
      - schema/functions/*
    when: always
  when: never
    
staging:
  stage: staging
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$GIT_SSH_PKEY")
    - git config --global url."ssh://git@g.ghn.vn".insteadOf "https://gido.vn"
    - git config --global user.email "gitbot@gido.vn"
    - git config --global user.name "Mr. Robot"
    - export CI_PUSH_REPO=git$(echo $CI_REPOSITORY_URL | grep -o "@.*" | sed "s/\//:/")
    - echo $CI_PUSH_REPO
    - git remote set-url --push origin ${CI_PUSH_REPO}
    - git status
    - go get -u gido.vn/gic/databases/sqitch.git/scripts/deploy-sqitch
  script:
    - make deploy_stag
    - 'git branch -D tmp_branch || true'
    - git status
    - 'git checkout -b tmp_branch && git add schema/.restricted/ && git commit -m "[ROBOT] Auto update .restricted folder from [${CI_JOB_ID}](${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID})" && git push origin tmp_branch:staging'
    - 'curl -X POST ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/merge_requests -H "Content-Type: application/json" -H "PRIVATE-TOKEN: ${API_TOKEN}" -d "{\"id\": \"${CI_PROJECT_ID}\", \"source_branch\": \"staging\", \"target_branch\": \"master\", \"title\": \"[ROBOT] Auto create merge request from staging to master\"}"'
  only:
    refs:
      - staging
    changes:
      - sqitch.plan
      - deploy/*
  when: manual
  except:
    refs:
      - merge_request

production:
  stage: production
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$GIT_SSH_PKEY")
    - git config --global url."ssh://git@g.ghn.vn".insteadOf "https://gido.vn"
    - git config --global user.email "gitbot@gido.vn"
    - git config --global user.name "Mr. Robot"
    - export CI_PUSH_REPO=git$(echo $CI_REPOSITORY_URL | grep -o "@.*" | sed "s/\//:/")
    - echo $CI_PUSH_REPO
    - git remote set-url --push origin ${CI_PUSH_REPO}
    - git status
    - go get -u gido.vn/gic/databases/sqitch.git/scripts/deploy-sqitch
  script:
    - make deploy_prod
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      changes:
      - sqitch.plan
      - deploy/*
      when: manual
    - when: never
